# Generated by Django 4.1.7 on 2023-04-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='masaage',
            new_name='massage',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
