# Generated by Django 4.1.7 on 2023-04-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_masaage_contact_massage_remove_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sunject',
            new_name='subject',
        ),
    ]
