# Generated by Django 4.1.7 on 2023-04-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_sunject_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='massage',
            field=models.TextField(null=True),
        ),
    ]
